name: Ubuntu-clang

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: GetClang
      run : |
            wget https://apt.llvm.org/llvm.sh
            chmod +x llvm.sh
            sudo ./llvm.sh 18
            clang++-18 --version
    - name: Build
      # Build your program with gcc
      working-directory: ${{github.workspace}}
      run: bazel build --action_env=CXX=clang++-18 --action_env=CC=clang-18 ...

    - name: Test
      # Build and Execute tests
      working-directory: ${{github.workspace}}
      run: bazel test --action_env=CXX=clang++-18 --action_env=CC=clang-18 --test_output=errors ...