name: Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Test
      # Build and Execute tests
      working-directory: ${{github.workspace}}
      run: bazel test --action_env=CXX=g++ --action_env=CC=gcc --test_output=errors --cxxopt=-std=c++20 ...

    - name: TestCatch2
      working-directory: ${{github.workspace}}
      run: bazel run //:catch2_test --action_env=CXX=g++ --action_env=CC=gcc --test_output=errors --cxxopt=-std=c++20