name: Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_with_bazel:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2

      - name: Test
        working-directory: ${{github.workspace}}
        run: bazel test --test_output=errors --cxxopt=/std:c++20 ...

      - name: TestCatch2
        working-directory: ${{github.workspace}}
        run: bazel run //:catch2_test --test_output=errors --cxxopt=/std:c++20